### ISSUE TITLE
Graininess of demonstrative gifs in README

### ISSUE THREAD

**Issue by Jdogzz** [Vidianos-Giannitsis/zetteldesk.el#1] opened 2022-03-04 22:42 UTC
I found the demonstrative gifs in the README to be very grainy. I tried in Firefox (bad graininess) and Chromium (more moderate graininess), it might be worth remaking them. I attach a screenshot comparing the two rendering results (Chromium left, Firefox right).

![Screenshot 2022-03-04 144000](https://user-images.githubusercontent.com/2792697/156851761-37cf63bd-db6f-44c2-8ec1-f22439078a61.png)

**Comment by Vidianos-Giannitsis** [comment] 2022-03-04 23:00
Oh that's weird. I use a chromium based browser and the rendering seems ok to me, but yeah

**Comment by Vidianos-Giannitsis** [comment] 2022-03-04 23:04
Sorry for closing it I accidentally clicked it instead of comment

What I wanted to say is that the Chromium one felt ok to me, and wasn't aware that it doesn't render properly on Firefox. As I am really a beginner in this kind of thing, do you have any clue what the issue is.

For my setup, I recorded with OBS, edited and exported to gif with Kden Live @1080p 60 fps. My emacs theme is doom-palenight, compositor picom and I also have Gammy open for blue light filtering. Could any of these have affected it?

Thanks for pointing this out. Will get back to you tomorrow as I am going to sleep in a bit

**Comment by Jdogzz** [comment] 2022-03-06 17:22
I think grainy gifs are somewhat common, and after playing around with resizing a test gif from your batch in Firefox my guess is it's the zooming function that's in particular exaggerating the graininess. I tried some basic optimizations in GIMP but apparently the tool is not well suited for working with gifs since it limits their color palette. However, you may try the tool discussed in the top answer of this SE post:

[https://stackoverflow.com/questions/42980663/ffmpeg-high-quality-animated-gif](https://stackoverflow.com/questions/42980663/ffmpeg-high-quality-animated-gif)

which is this open source tool here:

[https://github.com/ImageOptim/gifski](https://github.com/ImageOptim/gifski)

Since I don't have access to your original video files I can't try this myself (feel free to attach one here if you'd like me to try before you invest any time in this, this really is a minor problem), but just based on the showcased gifs from the tool the results look quite nice.

**Comment by Vidianos-Giannitsis** [comment] 2022-03-06 17:30
Will give it a try when I have time (most likely tomorrow). Thanks for
looking it up :D

**Comment by Vidianos-Giannitsis** [comment] 2022-03-08 17:59
For an update, I have decided to improve the gifs a bit instead of just doing this, so it will be done in a few days

**Comment by Vidianos-Giannitsis** [comment] 2022-03-15 19:42
Ok, was rather busy this week, but I finally managed to do the improvements I wanted. I checked both on Chromium and FIrefox and the quality seems to be great now. As an improvement, the size was also reduced a bit without compromising on quality. Will keep this open for a bit in case I missed something and if there is nothing mentioned I will close this

**Closed as completed** 2022-03-17 12:46 UTC
